name: Run MATLAB Build on GitHub-Hosted Runner 
on: 
  workflow_dispatch
env:
  MLM_LICENSE_TOKEN: ${{ secrets.LICTOKEN }}
jobs:
  check_test:
    name: Run MATLAB Tests
    strategy:
      matrix:
        os: [ubuntu-latest]    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: MATLAB_Compiler         
          release: R2024a
      - name: Run build
        uses: matlab-actions/run-build@v2.4.0
        with:
          tasks: check test 
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          source-folder: source
      - uses: actions/upload-artifact@v2
        with:
          name: cc
          path: code-coverage/coverage.xml 
      - uses: actions/upload-artifact@v2
        with:          
          name: tr
          path: test-results/results.xml   
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/*.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: MATLAB Test Results            # Name of the check run which will be created
          path: test-results/*.xml    # Path to test results
          reporter: java-junit        # Format of test results
          
  deploy:
    name: Generate Deploy Artifacts
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: MATLAB_Compiler         
          release: R2024a
      - name: Run build
        uses: matlab-actions/run-build@v2.4.0
        with:
          tasks: pcode deploy            
      - name: Upload artifact
        uses: actions/upload-artifact@v4  
        with:          
          name: app-${{ matrix.os }}
          path: ./*standalone*/*timestable*
          

